### ISSUE TITLE
The pro migrator is not working for free licenses

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-confluence-migrator-pro#14]
Steps to reproduce :

* In a pristine XWiki instance in 14.10.16, install the confluence migrator pro
* Generate a free license for the `com.xwiki.confluencepro:application-confluence-migrator-pro-ui` corresponding to the instance ID on the store
* Go to the confluence migrator pro home page
* Observe that the missing license message appears

Marking as blocker as, per process, we usually generate free license for CRM clients and XWiki employees.

**Comment by aubincleme** [comment]
Quickly looking at the codebase, it seems that we have some hardcoded checks that will verify if the license is of type `PAYING`, but without checking for the type `FREE`. 

One example : https://github.com/xwikisas/application-confluence-migrator-pro/blob/d4f6c556a384fbc9a858b6c560d647104b820773/application-confluence-migrator-pro-ui/src/main/resources/ConfluenceMigratorPro/Code/MigrationSheet.xml#L345

(note : I have not checked the full codebase)

We could check if the license is of type `TRIAL` instead, maybe.

**Comment by mflorea** [comment]
> We could check if the license is of type TRIAL instead, maybe.

Definitely.

**Comment by trrenty** [comment]
Hello @mflorea @aubincleme . An application can have 3 types of license. `FREE`, `TRIAL` and `PAID`. When installing the application, the default license will be `FREE`. Getting a trial for the application will get you a `TRIAL` license and buying it will get you a `PAID` license (i think, correct me if i'm wrong). 

Currently, the code that checks for a license if the following:
```
#set ($license = $services.licensing.licensor.getLicenseForEntity($mainReference))
#if ($license.type == 'FREE')
  {{error}}#getMissingLicenseMessage('confluencepro.extension.name'){{/error}}
#else
  #if ($license.type == 'TRIAL')
    {{warning}}$services.localization.render('confluencepro.extension.missingLicense', ['[[', ">>path:#getLicensesAdminSectionURL]]"]){{/warning}}
  #end
#end
```
This means that if the application has just been installed and has the default `FREE` license, the error message will be displayed. Otherwise, if the license if either `TRIAL` or `PAID`, the application will work. Additionally for the `TRIAL` license, a warning will be displayed.

> Marking as blocker as, per process, we usually generate free license for CRM clients and XWiki employees.

It seems that there is one more case of `FREE` license from what I understand?

**Comment by aubincleme** [comment]
> It seems that there is one more case of FREE license from what I understand?

Yes, we use FREE licenses a lot, and when using FREE licenses, the application should behave the same way as with PAID licenses.

**Comment by trrenty** [comment]
When calling `Licensor.getLicense(EntityReference)` on the a freshly installed application, it returned a `License` of type `FREE`. This made me associate the `FREE` type with `no license`, so I displayed the error message. However, it was not a correct assumption. The `License` also needs to be signed for it to be valid
