### ISSUE TITLE
Add the option to overwrite pages

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-confluence-migrator-pro#37]
here is the SQ: 
A user imports a space from Confluence to XWiki 
The user modifies page "How-to article" on the Confluence side
The user exports the space
The user reimports the space in XWiki with the following config:
<img width="868" alt="overwrite-issue-3" src="https://github.com/xwikisas/application-confluence-migrator-pro/assets/35834028/3e465fdb-4294-4784-a24d-c3e81b8cab45">
<img width="877" alt="overwrite-issue-2" src="https://github.com/xwikisas/application-confluence-migrator-pro/assets/35834028/926b0d8b-8a80-4b67-8f4a-1deea253e7b8">
<img width="879" alt="overwrite-issue-1" src="https://github.com/xwikisas/application-confluence-migrator-pro/assets/35834028/cc6ec1bf-a777-4a84-bd95-76060bb693d6">

Result: all the pages get duplicated and the homepage of the updated space is uploaded as "<pagename>_2"
![image](https://github.com/xwikisas/application-confluence-migrator-pro/assets/35834028/f606afb6-faca-4aa0-bfa0-c6b991474c68)

Need: 
If a page already exists on XWiki and the configuration "DELETE EXISTING PAGE" is set to "true" (or a new configuration, if needed), overwrite the existing page with the one present in the export package.

**Comment by trrenty** [comment]
Hello, @snazare . The `delete existing page` configuration is for the output filter stream. If set to true, the documents would be deleted only if two filter streams would run back to back (without nested pages migration).

To achieve the desired behaviour, the nested pages migrator would need an additional configuration that will denote whether the documents should be overwritten on not. The default value could be `true`, in my opinion. I feel like it is natural to want the documents to be overwritten, rather than duplicated (but there might be valid cases to have it the other way around). WDYT?

On the confluence migrator side there wouldn't be any modification (if the default value is true), unless we want to let the users change this option. But since we currently don't allow the users to configure the nested pages migration, I don't think that would be the case (but I'm not sure what the users want).

**Comment by trrenty** [comment]
After some investigation, I have new findings. It seems that the Nested Pages Migrator already removes the documents that are found to be duplicated. When transforming a page into a nested page (PageA -> PageA.WebHome) it checks whether the latter exists or not. If it exists, it checks if the author, creator and content author are the same and it also checks  if the content of the two pages are identical. If they all check out, then the pages are deemed to be duplicate and the target page will be overwritten.

In our case, there is a problem. If a page from confluence contains an user mention, its migrated counterpart will have different content at each migration. This is because the filter stream converter needs to generate a `{{mention}}` macro from a given `<user>` tag. The mention macro requires an anchor parameter that is unique per document (this is accomplished by using some random characters).

Given this situation, I think we have some more possible solutions:

1. (NPM) Change the criteria used to determine if a document is duplicated - instead of checking if the contents are the same, check if the creation dates are the same. Thus a document is duplicated if they have the same author, content author, creator and creation date (and the same doc ref). In the case of confluence migrations, this should fix the issue without any complications because the imported documents will always have the same creation dates. A possible problem with this fix is the other use cases of NPM application. Maybe in other scenarios, the creation dates of the migrated documents are not the same.
2. (xwiki-contrib/confluence) Change the confluence-xml filter stream converter so that the generated mention macros will have a deterministic anchor. Maybe something like this `{userRef}-{pageref}-{n-th mention to x user in page}`. The problem with this might lie with whether we can easily have access to the data that we need to generate the anchor - such as the page reference but also the index of the mention to the same user in page. (there can be multiple mentions to the same user in one page and we will need to have a different anchor for each)
3. (Confluence Migrator pro) After the user selects the spaces that need migrating and before the filter stream conversion, delete the existing pages in those spaces.
4. Do nothing. The issue can be avoided by manually deleting the desired space before a migration. Alternatively, if the user is interested in a single page, they can make use of the `includedPages` advanced property: delete only the desired page and add its id to the property. This should result in only that page being imported.

I think I'm inclined to go with the third option. If two migrations are run back to back, the NPM step will always find the duplicates and delete them (except for the case of this issue and if the migrated pages are modified by some user). Im not sure, but I think for the users its the expected behaviour that running the same migration after they made some changes to the pages will overwrite them.

WDYT @snazare @raphj @mflorea

**Comment by trrenty** [comment]
Indeed. If we drop the need for the Nested Pages Migrator App the issue should not occur anymore. The issue was fixed when the dependency to confluence-xml was upgraded to the fix version of this issue https://jira.xwiki.org/browse/CONFLUENCE-196.
