### ISSUE TITLE
Missing history comments

### ISSUE THREAD

**Issue by oanat** [xwikisas/application-confluence-migrator-pro#47]
Steps to reproduce:
* create a few pages in Confluence with different history comments, e.g. 
![Screenshot 2023-12-14 at 11 50 16](https://github.com/xwikisas/application-confluence-migrator-pro/assets/370535/11b109b3-fc7c-4dd5-a3a6-7467d14cbb43)
![Screenshot 2023-12-14 at 11 50 32](https://github.com/xwikisas/application-confluence-migrator-pro/assets/370535/ec6c6578-112c-4471-97ce-f589c7d22478)
* export the space including them and start a migration to XWiki 15.10 with Confluence Migrator Application (Pro) 1.7.2

Results:
* Not all history comments are imported
* Technical messages are present in the comments
<img width="900" alt="Screenshot 2023-12-14 at 11 54 15" src="https://github.com/xwikisas/application-confluence-migrator-pro/assets/370535/98f8540f-8d06-4b84-b587-e76060a576a6">
<img width="910" alt="Screenshot 2023-12-14 at 11 54 44" src="https://github.com/xwikisas/application-confluence-migrator-pro/assets/370535/d026470e-ce33-4f9c-aeae-0383a2458eae">

Expected results:
* All history comments are imported from Confluence to XWiki

**Comment by snazare** [comment]
as this is a platform bug, we will provide a workaround for the Confluence Migration usecase.

**Comment by trrenty** [comment]
The issue was caused by this platform bug https://jira.xwiki.org/browse/XWIKI-21801.

To fix the issue, the user should have an xwiki instance newer or equal to the fix version of the platform bug (15.10.6)

To avoid that, I pushed a workaround that will override the problematic component with the version that contains the fix (if the instance is lower than 15.10.6).
